---
- name: Make sure Setapp is installed.
  homebrew_cask:
    name: setapp
    state: present
    accept_external_apps: yes

- name: Get the name of the Setapp Installer
  shell: >
    set -o pipefail && \
    brew cask info setapp | grep Installer | sed -e "s/ (/_/g" | cut -d "_" -f1
  register: installer_name
  args:
    executable: /bin/bash
  changed_when: false

- name: Get the basedir of the Setapp Installer
  shell:  >
    set -o pipefail && \
    brew cask info setapp | grep Caskroom | sed -e "s/ (/_/g" | cut -d "_" -f1
  register: installer_path
  args:
    executable: /bin/bash
  changed_when: false

- name: Define the full Setapp Installer path
  set_fact:
    setapp_installer_path: "{{ installer_path.stdout }}/{{ installer_name.stdout }}"
  when: installer_name is defined and installer_name.rc ==0 and installer_path is defined and installer_path.rc ==0
  changed_when: false

- name: Remove Setapp Installer from Quarantine
  command: xattr -d com.apple.quarantine "{{ setapp_installer_path }}"
  when: setapp_installer_path is defined and setapp_installer_path | length > 0

- name: Launch Setapp Installer
  command: open "{{ setapp_installer_path }}"
  when: setapp_installer_path is defined and setapp_installer_path | length > 0
  changed_when: false
  ignore_errors: yes
